name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clean Yarn Cache
        run: yarn cache clean

      - name: Remove old dist
        run: rm -rf docs/.vuepress/dist

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack (Yarn Berry)
        run: corepack enable

      - name: Install Dependencies
        run: yarn install

      - name: Build VuePress
        run: NODE_OPTIONS=--openssl-legacy-provider yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TIL_TOKEN }}
          publish_dir: docs/.vuepress/dist/
