name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: vuepress deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.TIL_TOKEN }}
        TARGET_REPO: wold21/TIL_Vue
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: build/
