name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
      
    - name: Set Timezone
      run: sudo timedatectl set-timezone Asia/Seoul 

    - name: Clean Yarn Cache
      run: yarn cache clean

    - name: Delete node_modules and yarn.lock
      run: |
        rm -rf node_modules
        rm -f yarn.lock

    - name: Install Dependencies
      run: yarn install

    - name: Verify Git Installation
      run: git --version

    - name: Verify Installation
      run: |
        echo "Verifying installation of @vuepress/plugin-last-updated"
        yarn list --pattern @vuepress/plugin-last-updated
        echo "Verifying installation of moment"
        yarn list --pattern moment

    - name: vuepress deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.TIL_TOKEN }}
        TARGET_REPO: wold21/TIL_Vue
        BUILD_SCRIPT: yarn build
        BUILD_DIR: build/
